package com.fudz.restau;

import com.fudz.custom.FudzFrame;
import com.fudz.custom.FudzToolbar;
import javax.swing.ImageIcon;

/**
 *
 * @author Rene Tajos Jr.
 */
public class LoginFormFrame extends FudzFrame {

    /**
     * Creates new form LoginFormFrame
     */
    public LoginFormFrame() {
        this.setResizable(false);
        
        // initialize components
        initComponents();
        
        /*
        * This will center the window
        */
        int widthGap = (int)Fudz.getScreenWidth() - this.getWidth();
        int heightGap = (int)Fudz.getScreenHeight() - this.getHeight();
        this.setBounds(widthGap/2, heightGap/2, this.getWidth(), this.getHeight());
        
        // set the toolbar listener
        fudzToolbar.setFudzToolbarMouseListener(new FudzToolbar.FudzToolbarMouseListener() {
            @Override
            public void onDragged(int frameX, int frameY) {
                LoginFormFrame.this.setLocation(frameX, frameY);
            }
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fudzToolbar = new com.fudz.custom.FudzToolbar(this);
        closeWindowBtn = new javax.swing.JLabel();
        minimizeBtn = new javax.swing.JLabel();
        loginFormMainPanel = new javax.swing.JPanel();
        loginPanel = new javax.swing.JPanel();
        kitchenLoginLbl = new javax.swing.JLabel();
        userMainPanel = new com.fudz.custom.RoundedPanel();
        userIconPanel = new com.fudz.custom.RoundedPanel();
        userIcon = new javax.swing.JLabel();
        userTxtField = new javax.swing.JTextField();
        passMainPanel = new com.fudz.custom.RoundedPanel();
        passIconPanel = new com.fudz.custom.RoundedPanel();
        passIcon = new javax.swing.JLabel();
        passTxtField = new javax.swing.JTextField();
        loginBtn = new com.fudz.custom.RoundedPanel();
        jLabel2 = new javax.swing.JLabel();
        bgPane = new javax.swing.JLayeredPane();
        filterPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bgPanel = new javax.swing.JPanel();
        bgImg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        fudzToolbar.setBackground(new java.awt.Color(218, 164, 0));

        closeWindowBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/close_window_25px.png"))); // NOI18N
        closeWindowBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeWindowBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeWindowBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeWindowBtnMouseExited(evt);
            }
        });

        minimizeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/minimize_window_25px.png"))); // NOI18N
        minimizeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizeBtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout fudzToolbarLayout = new javax.swing.GroupLayout(fudzToolbar);
        fudzToolbar.setLayout(fudzToolbarLayout);
        fudzToolbarLayout.setHorizontalGroup(
            fudzToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fudzToolbarLayout.createSequentialGroup()
                .addContainerGap(880, Short.MAX_VALUE)
                .addComponent(minimizeBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closeWindowBtn)
                .addContainerGap())
        );
        fudzToolbarLayout.setVerticalGroup(
            fudzToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(closeWindowBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(minimizeBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );

        loginPanel.setBackground(new java.awt.Color(250, 238, 202));

        kitchenLoginLbl.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 18)); // NOI18N
        kitchenLoginLbl.setForeground(new java.awt.Color(218, 164, 0));
        kitchenLoginLbl.setText("KITCHEN LOG-IN");

        userMainPanel.setBackgroundColor(new java.awt.Color(255, 255, 255));
        userMainPanel.setCornerRadius(30);
        userMainPanel.setBorderColor(new java.awt.Color(218,164,0));
        userMainPanel.setBackground(new java.awt.Color(255, 255, 255));

        userIconPanel.setBackground(new java.awt.Color(218, 164, 0));
        userIconPanel.setCornerRadius(30);

        userIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user_ic_20px.png"))); // NOI18N
        userIconPanel.add(userIcon);

        userTxtField.setBorder(null);

        javax.swing.GroupLayout userMainPanelLayout = new javax.swing.GroupLayout(userMainPanel);
        userMainPanel.setLayout(userMainPanelLayout);
        userMainPanelLayout.setHorizontalGroup(
            userMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userMainPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(userIconPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userTxtField, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                .addContainerGap())
        );
        userMainPanelLayout.setVerticalGroup(
            userMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userMainPanelLayout.createSequentialGroup()
                .addGroup(userMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(userTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userIconPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        userMainPanel.setBackgroundColor(new java.awt.Color(255, 255, 255));
        userMainPanel.setCornerRadius(30);
        passMainPanel.setBackground(new java.awt.Color(255, 255, 255));
        passMainPanel.setCornerRadius(30);
        passMainPanel.setBorderColor(new java.awt.Color(218,164,0));

        passIconPanel.setBackground(new java.awt.Color(218, 164, 0));
        passIconPanel.setCornerRadius(30);

        passIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/key_20px.png"))); // NOI18N
        passIconPanel.add(passIcon);

        passTxtField.setBorder(null);

        javax.swing.GroupLayout passMainPanelLayout = new javax.swing.GroupLayout(passMainPanel);
        passMainPanel.setLayout(passMainPanelLayout);
        passMainPanelLayout.setHorizontalGroup(
            passMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passMainPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(passIconPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passTxtField, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                .addContainerGap())
        );
        passMainPanelLayout.setVerticalGroup(
            passMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passMainPanelLayout.createSequentialGroup()
                .addGroup(passMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(passTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passIconPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        loginBtn.setBackground(new java.awt.Color(218, 164, 0));
        loginBtn.setCornerRadius(30);
        loginBtn.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 10));

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("LOGIN");
        loginBtn.add(jLabel2);

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addContainerGap(89, Short.MAX_VALUE)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kitchenLoginLbl))
                .addGap(78, 78, 78))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(kitchenLoginLbl)
                .addGap(18, 18, 18)
                .addComponent(userMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(passMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(148, Short.MAX_VALUE))
        );

        bgPane.setLayout(new javax.swing.OverlayLayout(bgPane));

        filterPanel.setBackground(new java.awt.Color(135, 101, 0, 127));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/200x-logo.png"))); // NOI18N

        javax.swing.GroupLayout filterPanelLayout = new javax.swing.GroupLayout(filterPanel);
        filterPanel.setLayout(filterPanelLayout);
        filterPanelLayout.setHorizontalGroup(
            filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 556, Short.MAX_VALUE)
            .addGroup(filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(filterPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        filterPanelLayout.setVerticalGroup(
            filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 526, Short.MAX_VALUE)
            .addGroup(filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(filterPanelLayout.createSequentialGroup()
                    .addGap(0, 172, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 173, Short.MAX_VALUE)))
        );

        bgPane.add(filterPanel);

        bgImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/login-bg516px.jpg"))); // NOI18N

        javax.swing.GroupLayout bgPanelLayout = new javax.swing.GroupLayout(bgPanel);
        bgPanel.setLayout(bgPanelLayout);
        bgPanelLayout.setHorizontalGroup(
            bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgPanelLayout.createSequentialGroup()
                .addComponent(bgImg, javax.swing.GroupLayout.PREFERRED_SIZE, 556, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        bgPanelLayout.setVerticalGroup(
            bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bgPane.add(bgPanel);

        javax.swing.GroupLayout loginFormMainPanelLayout = new javax.swing.GroupLayout(loginFormMainPanel);
        loginFormMainPanel.setLayout(loginFormMainPanelLayout);
        loginFormMainPanelLayout.setHorizontalGroup(
            loginFormMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginFormMainPanelLayout.createSequentialGroup()
                .addComponent(bgPane)
                .addGap(0, 0, 0)
                .addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        loginFormMainPanelLayout.setVerticalGroup(
            loginFormMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginFormMainPanelLayout.createSequentialGroup()
                .addGroup(loginFormMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bgPane, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fudzToolbar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(loginFormMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(fudzToolbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(loginFormMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeWindowBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeWindowBtnMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeWindowBtnMouseClicked

    private void closeWindowBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeWindowBtnMouseEntered
        closeWindowBtn.setIcon(new ImageIcon(getClass().getResource("/icons/close_filled_window_25px.png")));
    }//GEN-LAST:event_closeWindowBtnMouseEntered

    private void closeWindowBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeWindowBtnMouseExited
        closeWindowBtn.setIcon(new ImageIcon(getClass().getResource("/icons/close_window_25px.png")));
    }//GEN-LAST:event_closeWindowBtnMouseExited

    private void minimizeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeBtnMouseClicked
        this.setExtendedState(Fudz.WINDOW_MINIMIZE);
    }//GEN-LAST:event_minimizeBtnMouseClicked

    private void minimizeBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeBtnMouseEntered
        minimizeBtn.setIcon(new ImageIcon(getClass().getResource("/icons/minimize_filled_window_25px.png")));
    }//GEN-LAST:event_minimizeBtnMouseEntered

    private void minimizeBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeBtnMouseExited
        minimizeBtn.setIcon(new ImageIcon(getClass().getResource("/icons/minimize_window_25px.png")));
    }//GEN-LAST:event_minimizeBtnMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFormFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFormFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFormFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFormFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFormFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgImg;
    private javax.swing.JLayeredPane bgPane;
    private javax.swing.JPanel bgPanel;
    private javax.swing.JLabel closeWindowBtn;
    private javax.swing.JPanel filterPanel;
    private com.fudz.custom.FudzToolbar fudzToolbar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel kitchenLoginLbl;
    private com.fudz.custom.RoundedPanel loginBtn;
    private javax.swing.JPanel loginFormMainPanel;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JLabel minimizeBtn;
    private javax.swing.JLabel passIcon;
    private com.fudz.custom.RoundedPanel passIconPanel;
    private com.fudz.custom.RoundedPanel passMainPanel;
    private javax.swing.JTextField passTxtField;
    private javax.swing.JLabel userIcon;
    private com.fudz.custom.RoundedPanel userIconPanel;
    private com.fudz.custom.RoundedPanel userMainPanel;
    private javax.swing.JTextField userTxtField;
    // End of variables declaration//GEN-END:variables
}
