package com.fudz.restau;

import com.fudz.custom.FudzFrame;
import com.fudz.custom.FudzToolbar;
import com.fudz.fragments.CookingInProgFragment;
import com.fudz.fragments.OrdersFragmentPanel;
import java.awt.Color;
import java.awt.Component;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GraphicsEnvironment;
import java.awt.GridLayout;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author Fudz Restaurant
 */
public class WindowFrame extends FudzFrame {
    
    private Color menuLabelColor = new Color(183,138,0);
    
    private int lastWindowState = -1;
    
    private Database.Server DB;
    private final String mReference = "Sample";
    
    private int viewedScrn = Fudz.ORDERS_SCREEN;
    
    private int ordersFragmentPanelWidth = 0;
    private int ordersFragmentPanelHeight = 0;
    
    private FudzMouseListener fudzFrameMouseListener;
    private FudzToolbar.FudzToolbarMouseListener fudzToolbarMouseListener;
    
    public static boolean[] isResizingWindowOnDrag = {false, false};

    /**
     * Creates new form NewJFrame
     */
    public WindowFrame() {
        //Firebase.initialize();
        //DB = new Database.Server(mReference);
        
        initComponents();
        /*
        * This will resize the window frame to the device's screen sizes - 300
        * and will center the frame.
        */
        int newScreenWidth = (int)(Fudz.getScreenWidth() - 300);
        float rate = ((float)Fudz.getScreenWidth() - 300) / (float)Fudz.getScreenWidth();
        int newScreenHeight = (int)(Fudz.getScreenHeight() * rate);
        
        this.setBounds(300/2, ((int)Fudz.getScreenHeight()-newScreenHeight)/2, newScreenWidth, newScreenHeight);
        
        new UpdateFragmentsThread().start();
        // = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
        /* * * * * * * * * *
        * MOUSE LISTENERS
        * * * * * * * * * */
        // FRAME MOUSE LISTENER
        fudzFrameMouseListener = new FudzMouseListener() {
            @Override
            public void onPressed() {
                JPanel fragment = (JPanel)contentPanel.getComponent(0);
                columnPHolder = Fudz.getColumn(contentsScrollPane.getWidth(), fragment.getPreferredSize().width);
            }

            @Override
            public void onDragged() {
                // ** updates the fragments column every drag ** \\
                JPanel fragment = (JPanel)contentPanel.getComponent(0);
                final int column = Fudz.getColumn(contentsScrollPane.getWidth(), fragment.getPreferredSize().width);
                if (column != columnPHolder) {
                    pHolderCount = 0;
                    _updateScreen(viewedScrn);
                }
                // = = = = = = = = = = = = = = \\
            }
        };
        
        // TOOLBAR MOUSE LISTENER
        fudzToolbarMouseListener = (int frameX, int frameY) -> {
            // onDragged
            WindowFrame.this.setLocation(frameX, frameY);
        };
        
        // set the listeners
        this.setFudzMouseListener(fudzFrameMouseListener);
        fudzToolbar.setFudzToolbarMouseListener(fudzToolbarMouseListener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ordersFragment = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        table_ic = new javax.swing.JLabel();
        tableNumLbl = new javax.swing.JLabel();
        customers_ic = new javax.swing.JLabel();
        customersLbl = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        ordersLstPanel = new javax.swing.JPanel();
        ordersLst = new javax.swing.JList<>();
        addOnsPanel = new javax.swing.JPanel();
        addOnsLbl = new javax.swing.JLabel();
        addOnsList = new javax.swing.JPanel();
        cookNowBtn = new javax.swing.JPanel();
        cookNowLbl = new javax.swing.JLabel();
        timerLbl = new javax.swing.JLabel();
        ordersItemFragment = new javax.swing.JPanel();
        itemNameLbl = new javax.swing.JLabel();
        itemQtyLbl = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        logoOnMenu = new javax.swing.JLabel();
        ordersPanel = new javax.swing.JPanel();
        orders_ic = new javax.swing.JLabel();
        ordersLbl = new javax.swing.JLabel();
        cookingPanel = new javax.swing.JPanel();
        cooking_ic = new javax.swing.JLabel();
        cookingLbl = new javax.swing.JLabel();
        ready2ServePanel = new javax.swing.JPanel();
        ready_ic = new javax.swing.JLabel();
        rdy2ServeLbl = new javax.swing.JLabel();
        headingPanel = new javax.swing.JPanel();
        headingLbl = new javax.swing.JLabel();
        contentsScrollPane = new javax.swing.JScrollPane();
        contentPanel = new javax.swing.JPanel();
        fudzToolbar = new com.fudz.custom.FudzToolbar(this);
        closeWindowBtn = new javax.swing.JLabel();
        maximizeBtn = new javax.swing.JLabel();
        minimizeBtn = new javax.swing.JLabel();

        ordersFragment.setBackground(new java.awt.Color(252, 243, 236));
        ordersFragment.setAutoscrolls(true);

        headerPanel.setBackground(new java.awt.Color(252, 243, 236));

        table_ic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/table_ic_25px.png"))); // NOI18N

        tableNumLbl.setFont(new java.awt.Font("Californian FB", 1, 14)); // NOI18N
        tableNumLbl.setForeground(new java.awt.Color(0, 0, 0));
        tableNumLbl.setText("Table No.: 12");

        customers_ic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/customers_ic_25px.png"))); // NOI18N

        customersLbl.setFont(new java.awt.Font("Californian FB", 1, 14)); // NOI18N
        customersLbl.setForeground(new java.awt.Color(0, 0, 0));
        customersLbl.setText("Customers: 2");

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(table_ic, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tableNumLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(customers_ic, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(customersLbl)
                .addGap(33, 33, 33))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(customersLbl)
                    .addComponent(customers_ic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tableNumLbl)
                    .addComponent(table_ic, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)))
        );

        jSeparator1.setBackground(new java.awt.Color(195, 168, 67));
        jSeparator1.setForeground(new java.awt.Color(252, 243, 236));

        ordersLstPanel.setBackground(new Color(0, 0, 0, 0));
        ordersLstPanel.setLayout(new java.awt.GridLayout(2, 1));

        ordersLst.setBackground(new java.awt.Color(252, 243, 236));
        ordersLst.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ordersLst.setFont(new java.awt.Font("Californian FB", 1, 13)); // NOI18N
        ordersLst.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "  King Burger  x2", "  Pink Spaghetti  x2", "  Chicken Wings  x2", "  Item 4", "  Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        ordersLst.setSelectionBackground(new java.awt.Color(245, 170, 34));
        ordersLstPanel.add(ordersLst);

        addOnsPanel.setBackground(new java.awt.Color(252, 243, 236));
        addOnsPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addOnsPanel.setPreferredSize(addOnsPanel.getPreferredSize());

        addOnsLbl.setFont(new java.awt.Font("Californian FB", 1, 14)); // NOI18N
        addOnsLbl.setText("Add-ons:");

        javax.swing.GroupLayout addOnsListLayout = new javax.swing.GroupLayout(addOnsList);
        addOnsList.setLayout(addOnsListLayout);
        addOnsListLayout.setHorizontalGroup(
            addOnsListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        addOnsListLayout.setVerticalGroup(
            addOnsListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 135, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout addOnsPanelLayout = new javax.swing.GroupLayout(addOnsPanel);
        addOnsPanel.setLayout(addOnsPanelLayout);
        addOnsPanelLayout.setHorizontalGroup(
            addOnsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addOnsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addOnsLbl)
                .addContainerGap(251, Short.MAX_VALUE))
            .addComponent(addOnsList, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        addOnsPanelLayout.setVerticalGroup(
            addOnsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addOnsPanelLayout.createSequentialGroup()
                .addComponent(addOnsLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addOnsList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        ordersLstPanel.add(addOnsPanel);

        cookNowBtn.setBackground(new java.awt.Color(255, 51, 51));

        cookNowLbl.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        cookNowLbl.setForeground(new java.awt.Color(255, 255, 255));
        cookNowLbl.setText("Cook Now");

        javax.swing.GroupLayout cookNowBtnLayout = new javax.swing.GroupLayout(cookNowBtn);
        cookNowBtn.setLayout(cookNowBtnLayout);
        cookNowBtnLayout.setHorizontalGroup(
            cookNowBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cookNowBtnLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cookNowLbl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cookNowBtnLayout.setVerticalGroup(
            cookNowBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cookNowBtnLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(cookNowLbl)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        timerLbl.setText("jLabel1");

        javax.swing.GroupLayout ordersFragmentLayout = new javax.swing.GroupLayout(ordersFragment);
        ordersFragment.setLayout(ordersFragmentLayout);
        ordersFragmentLayout.setHorizontalGroup(
            ordersFragmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cookNowBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(headerPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addGroup(ordersFragmentLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(timerLbl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(ordersFragmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ordersFragmentLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(ordersLstPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        ordersFragmentLayout.setVerticalGroup(
            ordersFragmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ordersFragmentLayout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(352, 352, 352)
                .addComponent(timerLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cookNowBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
            .addGroup(ordersFragmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ordersFragmentLayout.createSequentialGroup()
                    .addContainerGap(59, Short.MAX_VALUE)
                    .addComponent(ordersLstPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(77, Short.MAX_VALUE)))
        );

        itemNameLbl.setText("Item Name Here");

        itemQtyLbl.setText("Qty Here");

        javax.swing.GroupLayout ordersItemFragmentLayout = new javax.swing.GroupLayout(ordersItemFragment);
        ordersItemFragment.setLayout(ordersItemFragmentLayout);
        ordersItemFragmentLayout.setHorizontalGroup(
            ordersItemFragmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ordersItemFragmentLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(itemNameLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(73, 73, 73)
                .addComponent(itemQtyLbl)
                .addGap(43, 43, 43))
        );
        ordersItemFragmentLayout.setVerticalGroup(
            ordersItemFragmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ordersItemFragmentLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(ordersItemFragmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemNameLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(itemQtyLbl))
                .addGap(8, 8, 8))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fudz Restaurant");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(335, 0));
        setUndecorated(true);
        setSize(new java.awt.Dimension(938, 490));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowDeiconified(java.awt.event.WindowEvent evt) {
                formWindowDeiconified(evt);
            }
        });

        mainPanel.setBackground(new java.awt.Color(251, 211, 87));
        mainPanel.setPreferredSize(new java.awt.Dimension(1351, 700));

        menuPanel.setBackground(new java.awt.Color(252, 243, 236));
        menuPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(218, 164, 0)));

        logoOnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/200x-logo.png"))); // NOI18N

        ordersPanel.setBackground(new java.awt.Color(218, 164, 0));
        ordersPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ordersPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ordersPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ordersPanelMouseExited(evt);
            }
        });

        orders_ic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        orders_ic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/orders_ic_colored_25px.png"))); // NOI18N
        orders_ic.setLabelFor(ordersLbl);
        orders_ic.setAlignmentX(0.5F);
        orders_ic.setIconTextGap(2);
        orders_ic.setMaximumSize(new java.awt.Dimension(30, 30));
        orders_ic.setPreferredSize(new java.awt.Dimension(30, 30));

        ordersLbl.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 16)); // NOI18N
        ordersLbl.setForeground(new java.awt.Color(255, 255, 255));
        ordersLbl.setText("Orders");

        javax.swing.GroupLayout ordersPanelLayout = new javax.swing.GroupLayout(ordersPanel);
        ordersPanel.setLayout(ordersPanelLayout);
        ordersPanelLayout.setHorizontalGroup(
            ordersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ordersPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(orders_ic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ordersLbl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ordersPanelLayout.setVerticalGroup(
            ordersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ordersPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ordersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(ordersLbl)
                    .addComponent(orders_ic, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        cookingPanel.setBackground(new java.awt.Color(252, 243, 236));
        cookingPanel.setPreferredSize(new java.awt.Dimension(232, 42));
        cookingPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cookingPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cookingPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cookingPanelMouseExited(evt);
            }
        });

        cooking_ic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cooking_colored_25px.png"))); // NOI18N
        cooking_ic.setLabelFor(ordersLbl);

        cookingLbl.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 16)); // NOI18N
        cookingLbl.setForeground(new java.awt.Color(183, 138, 0));
        cookingLbl.setText("Cooking");

        javax.swing.GroupLayout cookingPanelLayout = new javax.swing.GroupLayout(cookingPanel);
        cookingPanel.setLayout(cookingPanelLayout);
        cookingPanelLayout.setHorizontalGroup(
            cookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cookingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cooking_ic)
                .addGap(18, 18, 18)
                .addComponent(cookingLbl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cookingPanelLayout.setVerticalGroup(
            cookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cookingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(cookingLbl)
                    .addComponent(cooking_ic, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        ready2ServePanel.setBackground(new java.awt.Color(252, 243, 236));
        ready2ServePanel.setPreferredSize(new java.awt.Dimension(232, 42));
        ready2ServePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ready2ServePanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ready2ServePanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ready2ServePanelMouseExited(evt);
            }
        });

        ready_ic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ready_to_serve_25px.png"))); // NOI18N
        ready_ic.setLabelFor(ordersLbl);

        rdy2ServeLbl.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 16)); // NOI18N
        rdy2ServeLbl.setForeground(new java.awt.Color(183, 138, 0));
        rdy2ServeLbl.setText("Ready to Serve");

        javax.swing.GroupLayout ready2ServePanelLayout = new javax.swing.GroupLayout(ready2ServePanel);
        ready2ServePanel.setLayout(ready2ServePanelLayout);
        ready2ServePanelLayout.setHorizontalGroup(
            ready2ServePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ready2ServePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ready_ic)
                .addGap(18, 18, 18)
                .addComponent(rdy2ServeLbl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ready2ServePanelLayout.setVerticalGroup(
            ready2ServePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ready2ServePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ready2ServePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(rdy2ServeLbl)
                    .addComponent(ready_ic, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addContainerGap(32, Short.MAX_VALUE)
                        .addComponent(logoOnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE))
                    .addComponent(ready2ServePanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                    .addComponent(cookingPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                    .addComponent(ordersPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(logoOnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                .addGap(41, 41, 41)
                .addComponent(ordersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(cookingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(ready2ServePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(240, Short.MAX_VALUE))
        );

        headingPanel.setBackground(new java.awt.Color(252, 242, 230));
        headingPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 15));

        headingLbl.setFont(new java.awt.Font("Californian FB", 1, 48)); // NOI18N
        headingLbl.setForeground(new java.awt.Color(183, 138, 0));
        headingLbl.setText("Customer Orders");
        headingPanel.add(headingLbl);

        contentsScrollPane.getVerticalScrollBar().setUnitIncrement(16);
        contentsScrollPane.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));

        contentPanel.setBackground(new java.awt.Color(251, 211, 87));
        contentPanel.setForeground(new java.awt.Color(51, 51, 51));
        contentPanel.setLayout(new java.awt.GridLayout(3, 2, 10, 20));
        contentsScrollPane.setViewportView(contentPanel);

        fudzToolbar.setBackground(new java.awt.Color(218, 164, 0));

        closeWindowBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/close_window_25px.png"))); // NOI18N
        closeWindowBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeWindowBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeWindowBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeWindowBtnMouseExited(evt);
            }
        });

        maximizeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/full_screen_25px.png"))); // NOI18N
        maximizeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                maximizeBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                maximizeBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                maximizeBtnMouseExited(evt);
            }
        });

        minimizeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/minimize_window_25px.png"))); // NOI18N
        minimizeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizeBtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout fudzToolbarLayout = new javax.swing.GroupLayout(fudzToolbar);
        fudzToolbar.setLayout(fudzToolbarLayout);
        fudzToolbarLayout.setHorizontalGroup(
            fudzToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fudzToolbarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(minimizeBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(maximizeBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closeWindowBtn)
                .addContainerGap())
        );
        fudzToolbarLayout.setVerticalGroup(
            fudzToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(closeWindowBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(maximizeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(minimizeBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(headingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1081, Short.MAX_VALUE)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(contentsScrollPane)
                        .addGap(19, 19, 19))))
            .addComponent(fudzToolbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(fudzToolbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(headingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(contentsScrollPane)
                        .addGap(37, 37, 37))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeWindowBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeWindowBtnMouseEntered
        if (!isResizingWindowOnDrag[1]) {
            closeWindowBtn.setIcon(new ImageIcon(getClass().getResource("/icons/close_filled_window_25px.png")));
            this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
            return;
        }
    }//GEN-LAST:event_closeWindowBtnMouseEntered

    private void closeWindowBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeWindowBtnMouseExited
        closeWindowBtn.setIcon(new ImageIcon(getClass().getResource("/icons/close_window_25px.png")));
    }//GEN-LAST:event_closeWindowBtnMouseExited

    private void closeWindowBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeWindowBtnMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeWindowBtnMouseClicked

    private void maximizeBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maximizeBtnMouseEntered
        if (!isResizingWindowOnDrag[1]) {
            maximizeBtn.setIcon(new ImageIcon(getClass().getResource("/icons/normal_window_25px.png")));
            this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
            isResizingWindowOnDrag[1] = false;
            
            if (this.getExtendedState() != Fudz.WINDOW_MAXIMIZE) {
                maximizeBtn.setIcon(new ImageIcon(getClass().getResource("/icons/maximized_stretch_25px.png")));
                return;
            }
        }
    }//GEN-LAST:event_maximizeBtnMouseEntered

    private void maximizeBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maximizeBtnMouseExited
        maximizeBtn.setIcon(new ImageIcon(getClass().getResource("/icons/full_screen_25px.png")));
    }//GEN-LAST:event_maximizeBtnMouseExited

    private void maximizeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maximizeBtnMouseClicked
        pHolderCount = 0;
        if (this.getExtendedState() != Fudz.WINDOW_MAXIMIZE) {
            _maximizeFrame();
            
            maximizeBtn.setIcon(new ImageIcon(getClass().getResource("/icons/full_screen_25px.png")));
            
            /*
            * This will update the grid layout every maximize view in the background thread
            */
            new UpdateFragmentsThread().start();
            
            return;
        }
        
        lastWindowState = Fudz.WINDOW_NORMAL;
        this.setExtendedState(Fudz.WINDOW_NORMAL);
        maximizeBtn.setIcon(new ImageIcon(getClass().getResource("/icons/full_screen_25px.png")));
        new UpdateFragmentsThread().start();
    }//GEN-LAST:event_maximizeBtnMouseClicked

    private void minimizeBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeBtnMouseEntered
        if (!isResizingWindowOnDrag[1]) {
            minimizeBtn.setIcon(new ImageIcon(getClass().getResource("/icons/minimize_filled_window_25px.png")));
            this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        }
    }//GEN-LAST:event_minimizeBtnMouseEntered

    private void minimizeBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeBtnMouseExited
        minimizeBtn.setIcon(new ImageIcon(getClass().getResource("/icons/minimize_window_25px.png")));
    }//GEN-LAST:event_minimizeBtnMouseExited

    private void minimizeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeBtnMouseClicked
        this.setExtendedState(Fudz.WINDOW_MINIMIZE);
    }//GEN-LAST:event_minimizeBtnMouseClicked

    private void formWindowDeiconified(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowDeiconified
        if (lastWindowState == Fudz.WINDOW_MAXIMIZE)
            _maximizeFrame();
    }//GEN-LAST:event_formWindowDeiconified

    
        
    
    private void cookingPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cookingPanelMouseEntered
        if (isResizingWindowOnDrag[0])
            return;
        
        this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR)); // always set the cursor to default
        
        if (viewedScrn == Fudz.COOKING_SCREEN)
            return;
        
        cookingPanel.setBackground(Fudz.mouseEnteredOnMenuTabs_COLOR);
    }//GEN-LAST:event_cookingPanelMouseEntered

    private void cookingPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cookingPanelMouseExited
        if (viewedScrn == Fudz.COOKING_SCREEN)
            return;
        
        cookingPanel.setBackground(Fudz.mouseExitedOnMenuTabs_COLOR);
    }//GEN-LAST:event_cookingPanelMouseExited

    private void cookingPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cookingPanelMouseClicked
        pHolderCount = 0; // always reset the place holder count when changing screen
        if (viewedScrn == Fudz.COOKING_SCREEN)
            return;
        
        cookingPanel.setBackground(Fudz.mouseClickedOnMenuTabs_COLOR);
        cookingLbl.setForeground(Color.WHITE);
        _unHighlightMenuTab(); // unhighlight the previous menu tab.
        viewedScrn = Fudz.COOKING_SCREEN; // set the viewed screen to cooking screen.
        _updateScreen(Fudz.COOKING_SCREEN);
    }//GEN-LAST:event_cookingPanelMouseClicked

    private void ordersPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ordersPanelMouseEntered
        if (isResizingWindowOnDrag[0])
            return;
        
        this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR)); // always set the cursor to default
        
        if (viewedScrn == Fudz.ORDERS_SCREEN)
            return;
        
        ordersPanel.setBackground(Fudz.mouseEnteredOnMenuTabs_COLOR);
    }//GEN-LAST:event_ordersPanelMouseEntered

    private void ordersPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ordersPanelMouseExited
        if (viewedScrn == Fudz.ORDERS_SCREEN)
            return;
        
        ordersPanel.setBackground(Fudz.mouseExitedOnMenuTabs_COLOR);
    }//GEN-LAST:event_ordersPanelMouseExited

    private void ordersPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ordersPanelMouseClicked
        pHolderCount = 0; // always reset the placeholder count when changing screens
        if (viewedScrn == Fudz.ORDERS_SCREEN)
            return;
        
        ordersPanel.setBackground(Fudz.mouseClickedOnMenuTabs_COLOR);
        ordersLbl.setForeground(Color.WHITE);
        _unHighlightMenuTab(); // unhighlight the previous menu tab.
        viewedScrn = Fudz.ORDERS_SCREEN; // set the viewed screen to orders screen.
        _updateScreen(Fudz.ORDERS_SCREEN);
    }//GEN-LAST:event_ordersPanelMouseClicked

    private void ready2ServePanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ready2ServePanelMouseEntered
        if (isResizingWindowOnDrag[0])
            return;
        
        this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR)); // always set the cursor to default
        
        if (viewedScrn == Fudz.RTS_SCREEN)
            return;
        
        ready2ServePanel.setBackground(Fudz.mouseEnteredOnMenuTabs_COLOR);
    }//GEN-LAST:event_ready2ServePanelMouseEntered

    private void ready2ServePanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ready2ServePanelMouseExited
        if (viewedScrn == Fudz.RTS_SCREEN)
            return;
        
        ready2ServePanel.setBackground(Fudz.mouseExitedOnMenuTabs_COLOR);
    }//GEN-LAST:event_ready2ServePanelMouseExited

    private void ready2ServePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ready2ServePanelMouseClicked
        pHolderCount = 0; // always reset the placeholder count when changing screens
        if (viewedScrn == Fudz.RTS_SCREEN)
            return;
        
        ready2ServePanel.setBackground(Fudz.mouseClickedOnMenuTabs_COLOR);
        rdy2ServeLbl.setForeground(Color.WHITE);
        _unHighlightMenuTab(); // unhighlight the previous menu tab.
        viewedScrn = Fudz.RTS_SCREEN; // set the viewed screen to orders screen.
    }//GEN-LAST:event_ready2ServePanelMouseClicked

    /* * * * * * * * *
    * CUSTOM METHODS
    * * * * * * * * */
    // this will update the screen when a certain menu tab is click.
    private void _updateScreen(final int screen) {
        switch (screen) {
            case Fudz.ORDERS_SCREEN:
                headingPanel.removeAll();
                contentPanel.removeAll();
                headingPanel.add(headingLbl);
                _addOrder();
                headingPanel.updateUI(); contentPanel.updateUI(); // always update the UI to avoid distorted or not visible graphics
                break;
            case Fudz.COOKING_SCREEN:
                headingPanel.removeAll();
                contentPanel.removeAll();
                
                _addCooking();
                headingPanel.updateUI(); contentPanel.updateUI(); // always update the UI to avoid distorted or not visible graphics
                break;
            case Fudz.RTS_SCREEN:
                break;
        }
    }
    
    // this will unhighlight the previous highlighted menu tab.
    private void _unHighlightMenuTab() {
        switch (viewedScrn) {
            case Fudz.ORDERS_SCREEN:
                ordersPanel.setBackground(new Color(252,243,236));
                ordersLbl.setForeground(menuLabelColor);
                break;
            case Fudz.COOKING_SCREEN:
                cookingPanel.setBackground(new Color(252,243,236));
                cookingLbl.setForeground(menuLabelColor);
                break;
            case Fudz.RTS_SCREEN:
                ready2ServePanel.setBackground(new Color(252,243,236));
                rdy2ServeLbl.setForeground(menuLabelColor);
                break;
        }
    }
    
    private void _maximizeFrame() {
        lastWindowState = Fudz.WINDOW_MAXIMIZE;
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        GraphicsEnvironment env = GraphicsEnvironment.getLocalGraphicsEnvironment();  
        this.setMaximizedBounds(env.getMaximumWindowBounds());
    }
    
    private int columnPHolder = 0;
    
    private void _resetGridLayout(Component comp, int size, int column) {
        int row; float remainder;
        
        row = size / column;
        remainder = size % column;

        ((JPanel)comp).setLayout(new GridLayout(remainder!=0.0?row + 1:row, column, 5, 10));
    }
    
    private int pHolderCount = 0, columnNum = 0;
    private void _addFragment(final JPanel pContentPanel, JPanel _fragment) {
        final JPanel fragment = _fragment;
        final int column = Fudz.getColumn(contentsScrollPane.getWidth(), fragment.getPreferredSize().width);
        
        columnNum = column; columnPHolder = column;
        int childrensCount = pContentPanel.getComponentCount() + 1;
        // when the screen is on ORDERS
        if (viewedScrn == Fudz.ORDERS_SCREEN) {
            
            _initFragments(fragment, childrensCount, column);

            if (ordersFragmentPanelWidth == 0)
                ordersFragmentPanelWidth = fragment.getPreferredSize().width;
            if (ordersFragmentPanelHeight == 0)
                ordersFragmentPanelHeight = fragment.getPreferredSize().height;
            
            // when the screen is on COOKING
        } else if (viewedScrn == Fudz.COOKING_SCREEN) {
            _initFragments(fragment, childrensCount, column);
        }
    }
    
    private void _initFragments(final JPanel fragment, final int _childrensCount, final int column) {
            int childrensCount = _childrensCount;
            // if the ordersFragmentPanel children count is less than or equal 2
            // then, set its layout manager first to flow layout to avoid fragment stretching effect.
            if (childrensCount-pHolderCount <= column) {
                contentPanel.setLayout(new FlowLayout());
                contentPanel.add(fragment);
                return;
            }
            // else
            
            if (pHolderCount > 0) {
                childrensCount -= pHolderCount;
                contentPanel.remove(contentPanel.getComponentCount()-1);
                pHolderCount--;
            }
            
            int absChildCount = contentPanel.getComponentCount()-pHolderCount;
            _resetGridLayout(contentPanel, childrensCount, column);
            contentPanel.add(fragment, pHolderCount!=0? absChildCount : contentPanel.getComponentCount()-1);
            
            if (pHolderCount > 0) // always return if there's already a place holder
                return;
            
            // this will fix or add placeholders to avoid stretching effect.
            Fudz.fixGridLayout(contentPanel, viewedScrn, _pHolderCount(column));
    }
    
    private int _pHolderCount(final int column) {
        while (columnNum < contentPanel.getComponentCount())
            columnNum += column;
            
        return pHolderCount = columnNum - contentPanel.getComponentCount(); // how many place holder to add
    }
    
    /*
    * THIS METHOD IS FOR TESTING AND TO BE REMOVED LATER.
    */
    private void _addOrder() {
        _addFragment(contentPanel, new OrdersFragmentPanel());
        _addFragment(contentPanel, new OrdersFragmentPanel());
        _addFragment(contentPanel, new OrdersFragmentPanel());
        _addFragment(contentPanel, new OrdersFragmentPanel());
        _addFragment(contentPanel, new OrdersFragmentPanel());
        _addFragment(contentPanel, new OrdersFragmentPanel());
        _addFragment(contentPanel, new OrdersFragmentPanel());
        _addFragment(contentPanel, new OrdersFragmentPanel());
        _addFragment(contentPanel, new OrdersFragmentPanel());
        _addFragment(contentPanel, new OrdersFragmentPanel());
    }
    
    private void _addCooking() {
        _addFragment(contentPanel, new CookingInProgFragment());
        _addFragment(contentPanel, new CookingInProgFragment());
        _addFragment(contentPanel, new CookingInProgFragment());
        _addFragment(contentPanel, new CookingInProgFragment());
        _addFragment(contentPanel, new CookingInProgFragment());
        _addFragment(contentPanel, new CookingInProgFragment());
        _addFragment(contentPanel, new CookingInProgFragment());
        _addFragment(contentPanel, new CookingInProgFragment());
    }
    
    /*
    * This will update the screen or the fragments 
    * layout everytime the window frame state changed
    * - -
    * We update it in the background thread so it can
    * properly update the screen or the fragments layout
    */
    private class UpdateFragmentsThread extends Thread {
        
        private boolean isFirstInit = true;
        
        @Override
        public void run() {
            
            _updateScreen(viewedScrn);
            
            if (isFirstInit) {
                WindowFrame.this.setMinimumSize(new Dimension(menuPanel.getWidth()+18+ordersFragmentPanelWidth+19+20, ordersFragmentPanelHeight+115));
                isFirstInit = false;
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WindowFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WindowFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WindowFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WindowFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new WindowFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addOnsLbl;
    private javax.swing.JPanel addOnsList;
    private javax.swing.JPanel addOnsPanel;
    private javax.swing.JLabel closeWindowBtn;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JScrollPane contentsScrollPane;
    private javax.swing.JPanel cookNowBtn;
    private javax.swing.JLabel cookNowLbl;
    private javax.swing.JLabel cookingLbl;
    private javax.swing.JPanel cookingPanel;
    private javax.swing.JLabel cooking_ic;
    private javax.swing.JLabel customersLbl;
    private javax.swing.JLabel customers_ic;
    private com.fudz.custom.FudzToolbar fudzToolbar;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel headingLbl;
    private javax.swing.JPanel headingPanel;
    private javax.swing.JLabel itemNameLbl;
    private javax.swing.JLabel itemQtyLbl;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel logoOnMenu;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel maximizeBtn;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JLabel minimizeBtn;
    private javax.swing.JPanel ordersFragment;
    private javax.swing.JPanel ordersItemFragment;
    private javax.swing.JLabel ordersLbl;
    private javax.swing.JList<String> ordersLst;
    private javax.swing.JPanel ordersLstPanel;
    private javax.swing.JPanel ordersPanel;
    private javax.swing.JLabel orders_ic;
    private javax.swing.JLabel rdy2ServeLbl;
    private javax.swing.JPanel ready2ServePanel;
    private javax.swing.JLabel ready_ic;
    private javax.swing.JLabel tableNumLbl;
    private javax.swing.JLabel table_ic;
    private javax.swing.JLabel timerLbl;
    // End of variables declaration//GEN-END:variables
}
