package com.fudz.fragments;

import com.fudz.custom.FudzJList;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.border.Border;
import javax.swing.border.SoftBevelBorder;

/**
 *
 * @author Rene Tajos Jr.
 * This is a fragment/JPanel for the
 * orders of our customer.
 * This is the panel where we can view
 * the orders that the waiters sent
 * from our mobile application
 */
public class OrdersFragment extends javax.swing.JPanel {
    
    private final Font ordersLst_font = new Font("Californian FB", 1, 14);
    private final Color ordersLst_BgColor = new Color(252,243,236);
    private final Border ordersLst_Border = new SoftBevelBorder(javax.swing.border.BevelBorder.RAISED);
    
    private final Font addOnsLst_font = new Font("Californian FB", 1, 14);
    private final Color addOnsLst_BgColor = new Color(252,243,236);
    private final Border addOnsLst_Border = BorderFactory.createEmptyBorder(1, 1, 1, 1);
    
    private final Color addOnsPanel_BgColor = new Color(252,243,236);
    private final Border addOnsPanel_Border = new SoftBevelBorder(javax.swing.border.BevelBorder.RAISED);

    /**
     * Creates new form OrdersFragment
     */
    public OrdersFragment() {
        initComponents();
        
        /*
        **
        * THIS IS FOR EXAMPLE ONLY - TO BE REMOVED LATER
        * JUST TO POPULATE THE LIST
        */
        
        timerLbl.setText("Time Approx.: 12 minutes to finish");
        
        // ordersLst
        ordersLst.setFont(ordersLst_font);
        List<HashMap<String, Object>> items = new ArrayList<>();
        {
            HashMap<String, Object> map = new HashMap<>();
            map.put(FudzJList.ITEM_NAME_KEY, "Cheese Burger King");
            map.put(FudzJList.ITEM_QTY_KEY, 3);
            items.add(map);
            
            map = new HashMap<>();
            map.put(FudzJList.ITEM_NAME_KEY, "Spaghetti");
            map.put(FudzJList.ITEM_QTY_KEY, 2);
            items.add(map);
            
            map = new HashMap<>();
            map.put(FudzJList.ITEM_NAME_KEY, "Mammon");
            map.put(FudzJList.ITEM_QTY_KEY, 5);
            items.add(map);
            
            map = new HashMap<>();
            map.put(FudzJList.ITEM_NAME_KEY, "Fried Chicken");
            map.put(FudzJList.ITEM_QTY_KEY, 5);
            items.add(map);
        }
        ordersLst.setData(items);
        
        // addOns List
        addOnsList.setFont(addOnsLst_font);
        List<HashMap<String, Object>> items2 = new ArrayList<>();
        {
            HashMap<String, Object> map = new HashMap<>();
            map.put(FudzJList.ITEM_NAME_KEY, "Cheese Burger King");
            map.put(FudzJList.ITEM_QTY_KEY, 3);
            items2.add(map);
            
            map = new HashMap<>();
            map.put(FudzJList.ITEM_NAME_KEY, "Spaghetti");
            map.put(FudzJList.ITEM_QTY_KEY, 2);
            items2.add(map);
            
            map = new HashMap<>();
            map.put(FudzJList.ITEM_NAME_KEY, "Mammon");
            map.put(FudzJList.ITEM_QTY_KEY, 5);
            items2.add(map);
            
            map = new HashMap<>();
            map.put(FudzJList.ITEM_NAME_KEY, "Fried Chicken");
            map.put(FudzJList.ITEM_QTY_KEY, 5);
            items2.add(map);
        }
        addOnsList.setData(items2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ordersFragment = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        table_ic = new javax.swing.JLabel();
        tableNumLbl = new javax.swing.JLabel();
        customers_ic = new javax.swing.JLabel();
        customersLbl = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        ordersLstPanel = new javax.swing.JPanel();
        ordersScrollPane = new javax.swing.JScrollPane();
        ordersLst = new com.fudz.custom.FudzJList();
        addOnsPanel = new javax.swing.JPanel();
        addOnsLbl = new javax.swing.JLabel();
        addOnsScrollPane = new javax.swing.JScrollPane();
        addOnsList = new com.fudz.custom.FudzJList();
        cookNowBtn = new javax.swing.JPanel();
        cookNowLbl = new javax.swing.JLabel();
        timerLbl = new javax.swing.JLabel();

        ordersFragment.setBackground(new java.awt.Color(252, 243, 236));
        ordersFragment.setAutoscrolls(true);
        ordersFragment.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                ordersFragmentComponentResized(evt);
            }
        });

        headerPanel.setBackground(new java.awt.Color(252, 243, 236));

        table_ic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/table_ic_25px.png"))); // NOI18N

        tableNumLbl.setFont(new java.awt.Font("Californian FB", 1, 14)); // NOI18N
        tableNumLbl.setForeground(new java.awt.Color(0, 0, 0));
        tableNumLbl.setText("Table No.: 12");

        customers_ic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/customers_ic_25px.png"))); // NOI18N

        customersLbl.setFont(new java.awt.Font("Californian FB", 1, 14)); // NOI18N
        customersLbl.setForeground(new java.awt.Color(0, 0, 0));
        customersLbl.setText("Customers: 2");

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(table_ic, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tableNumLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(customers_ic, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(customersLbl)
                .addGap(33, 33, 33))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(customersLbl)
                    .addComponent(customers_ic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tableNumLbl)
                    .addComponent(table_ic, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)))
        );

        jSeparator1.setBackground(new java.awt.Color(195, 168, 67));
        jSeparator1.setForeground(new java.awt.Color(252, 243, 236));

        ordersLstPanel.setBackground(new java.awt.Color(0, 0, 0, 0));
        ordersLstPanel.setLayout(new java.awt.GridLayout(2, 1));

        ordersScrollPane.setBorder(null);
        ordersScrollPane.getVerticalScrollBar().setUnitIncrement(16);

        ordersLst.setBackground(new java.awt.Color(252, 243, 236));
        ordersLst.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout ordersLstLayout = new javax.swing.GroupLayout(ordersLst);
        ordersLst.setLayout(ordersLstLayout);
        ordersLstLayout.setHorizontalGroup(
            ordersLstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 316, Short.MAX_VALUE)
        );
        ordersLstLayout.setVerticalGroup(
            ordersLstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 165, Short.MAX_VALUE)
        );

        ordersScrollPane.setViewportView(ordersLst);

        ordersLstPanel.add(ordersScrollPane);

        addOnsPanel.setBackground(new java.awt.Color(252, 243, 236));
        addOnsPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addOnsPanel.setPreferredSize(addOnsPanel.getPreferredSize());

        addOnsLbl.setFont(new java.awt.Font("Californian FB", 1, 14)); // NOI18N
        addOnsLbl.setText("Add-ons:");

        addOnsScrollPane.getVerticalScrollBar().setUnitIncrement(16);
        addOnsScrollPane.setBorder(null);

        addOnsList.setBackground(new java.awt.Color(252, 243, 236));

        javax.swing.GroupLayout addOnsListLayout = new javax.swing.GroupLayout(addOnsList);
        addOnsList.setLayout(addOnsListLayout);
        addOnsListLayout.setHorizontalGroup(
            addOnsListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );
        addOnsListLayout.setVerticalGroup(
            addOnsListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 138, Short.MAX_VALUE)
        );

        addOnsScrollPane.setViewportView(addOnsList);

        javax.swing.GroupLayout addOnsPanelLayout = new javax.swing.GroupLayout(addOnsPanel);
        addOnsPanel.setLayout(addOnsPanelLayout);
        addOnsPanelLayout.setHorizontalGroup(
            addOnsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addOnsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addOnsLbl)
                .addContainerGap(251, Short.MAX_VALUE))
            .addGroup(addOnsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(addOnsScrollPane))
        );
        addOnsPanelLayout.setVerticalGroup(
            addOnsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addOnsPanelLayout.createSequentialGroup()
                .addComponent(addOnsLbl)
                .addContainerGap(142, Short.MAX_VALUE))
            .addGroup(addOnsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addOnsPanelLayout.createSequentialGroup()
                    .addGap(0, 21, Short.MAX_VALUE)
                    .addComponent(addOnsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        ordersLstPanel.add(addOnsPanel);

        cookNowBtn.setBackground(new java.awt.Color(255, 51, 51));

        cookNowLbl.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        cookNowLbl.setForeground(new java.awt.Color(255, 255, 255));
        cookNowLbl.setText("Cook Now");

        javax.swing.GroupLayout cookNowBtnLayout = new javax.swing.GroupLayout(cookNowBtn);
        cookNowBtn.setLayout(cookNowBtnLayout);
        cookNowBtnLayout.setHorizontalGroup(
            cookNowBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cookNowBtnLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cookNowLbl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cookNowBtnLayout.setVerticalGroup(
            cookNowBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cookNowBtnLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(cookNowLbl)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        timerLbl.setText("jLabel1");

        javax.swing.GroupLayout ordersFragmentLayout = new javax.swing.GroupLayout(ordersFragment);
        ordersFragment.setLayout(ordersFragmentLayout);
        ordersFragmentLayout.setHorizontalGroup(
            ordersFragmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cookNowBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(headerPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addGroup(ordersFragmentLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(timerLbl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(ordersFragmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ordersFragmentLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(ordersLstPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        ordersFragmentLayout.setVerticalGroup(
            ordersFragmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ordersFragmentLayout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(352, 352, 352)
                .addComponent(timerLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cookNowBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
            .addGroup(ordersFragmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ordersFragmentLayout.createSequentialGroup()
                    .addContainerGap(59, Short.MAX_VALUE)
                    .addComponent(ordersLstPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(77, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 328, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(ordersFragment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 466, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(ordersFragment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ordersFragmentComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_ordersFragmentComponentResized
        // this will check if there are less items ordered,
        // if there are, we will remove the JScrollPane so
        // we can mouse scroll on the list efficiently.
        if (!(ordersScrollPane.getHeight() < ordersLst.getHeight())) {
            ordersLstPanel.remove(ordersScrollPane);

            ordersLst.setBackground(ordersLst_BgColor);
            ordersLst.setBorder(ordersLst_Border);
            ordersLst.setFont(ordersLst_font);

            ordersLstPanel.add(ordersLst, 0);
        }

        if (!(addOnsScrollPane.getHeight() < addOnsList.getHeight())) {
            addOnsPanel.remove(addOnsScrollPane);

            addOnsList.setBackground(addOnsLst_BgColor);
            addOnsList.setBorder(addOnsLst_Border);
            addOnsList.setFont(addOnsLst_font);

            addOnsPanel.setBackground(addOnsPanel_BgColor);
            addOnsPanel.setBorder(addOnsPanel_Border);
            addOnsPanel.setPreferredSize(addOnsPanel.getPreferredSize());
            javax.swing.GroupLayout addOnsPanelLayout = new javax.swing.GroupLayout(addOnsPanel);
            addOnsPanel.setLayout(addOnsPanelLayout);
            addOnsPanelLayout.setHorizontalGroup(
                addOnsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(addOnsPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(addOnsLbl)
                    .addContainerGap(251, Short.MAX_VALUE))
                .addComponent(addOnsList, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );
            addOnsPanelLayout.setVerticalGroup(
                addOnsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(addOnsPanelLayout.createSequentialGroup()
                    .addComponent(addOnsLbl)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addOnsList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap())
            );
        }
    }//GEN-LAST:event_ordersFragmentComponentResized


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addOnsLbl;
    private com.fudz.custom.FudzJList addOnsList;
    private javax.swing.JPanel addOnsPanel;
    private javax.swing.JScrollPane addOnsScrollPane;
    private javax.swing.JPanel cookNowBtn;
    private javax.swing.JLabel cookNowLbl;
    private javax.swing.JLabel customersLbl;
    private javax.swing.JLabel customers_ic;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel ordersFragment;
    private com.fudz.custom.FudzJList ordersLst;
    private javax.swing.JPanel ordersLstPanel;
    private javax.swing.JScrollPane ordersScrollPane;
    private javax.swing.JLabel tableNumLbl;
    private javax.swing.JLabel table_ic;
    private javax.swing.JLabel timerLbl;
    // End of variables declaration//GEN-END:variables
}
